### ISSUE TITLE
Boost dependency required while building project

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#10]
Some potential users of faker library asks for deleting boost dependency because they cannot afford to have this dependency. We could use [date lib](https://github.com/HowardHinnant/date) for replacing date operations or come up with other solution.

**Comment by dario-loi** [comment]
Utilizing the standard `chrono` library would remove the need for a dependency altogether: https://en.cppreference.com/w/cpp/chrono

**Comment by cieslarmichal** [comment]
Yes, it would be an important change to make in faker library. Good idea. I will try it. Would you like to work on doxygen? I actually created some config file for doxygen but I dont have any experience with that, could you take a look at this? (and this autodeploying).

https://github.com/cieslarmichal/faker-cxx/pull/12

**Comment by cieslarmichal** [comment]
Fixed in https://github.com/cieslarmichal/faker-cxx/pull/21
