### ISSUE TITLE
Add git module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#125]
Add a new module with following functionalities
- branch
- commitDate
- commitEntry
- commitMessage
- commitSha

**Comment by Pe7o** [comment]
Hello, could I please be assigned to this issue? Thanking you in anticipation.

**Comment by cieslarmichal** [comment]
Hello, yes, sure go ahead :) I assigned you to this issue. Dont forget to give a star to the project for gaining more popularity 🔥
