### ISSUE TITLE
Add location addresses data from Italia

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#155]

**Comment by joshhn** [comment]
Hi @cieslarmichal , can you assign me this issue?

**Comment by cieslarmichal** [comment]
Hello, sure, assigned :)
Please give a start to the project to make it more popular :star: :fire:

**Comment by cieslarmichal** [comment]
hello, how is it going? will you work on this issue or should I unassign the issue?

**Comment by joshhn** [comment]
Hey @cieslarmichal. Thanks for your reminder. I will work on this on this weekend.

**Comment by cieslarmichal** [comment]
Ok thanks

**Comment by cieslarmichal** [comment]
hey, how is it going? :)

**Comment by joshhn** [comment]
Hi @cieslarmichal, can you reassign me this issue? I'm available to work on that now.

**Comment by cieslarmichal** [comment]
Assigned
