### ISSUE TITLE
Add vehicle module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#156]
Add a new module with following functionalities

- bicycle
- color
- fuel
- manufacturer
- model
- type
- vehicle
- vin
- vrm

**Comment by SunHashira** [comment]
Hi, can I help you with this issue also ?

**Comment by cieslarmichal** [comment]
Hello, sure assigned :)
Please give a star to the project to make it more popular :star: :fire:

**Comment by cieslarmichal** [comment]
hello, how is it going? will you work on this issue or should I unassign the issue?

**Comment by SunHashira** [comment]
hi, im sorry it takes so long, ill work on it and it will ne done till next sunday if its okay ? Dňa 2. 11. 2023 o 10:05 užívateľ Michał Cieślar ***@***.***> napísal:﻿
hello, how is it going? will you work on this issue or should I unassign the issue?

**Comment by yakupcemilk** [comment]
Can I done this?

**Comment by cieslarmichal** [comment]
Ok, go ahead :)

**Comment by cieslarmichal** [comment]
hello, how is it going? :)

**Comment by MikelKokoshi** [comment]
Hi, i would like to work on this. Assign it to me please.
