### ISSUE TITLE
Add science module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#158]
Add a new module with following functionalities

- chemicalElement
- unit

**Comment by Shardul1908** [comment]
Hi,
So you want a module where we can get chemical element information?
Like the atomic number, Symbol, etc.

**Comment by cieslarmichal** [comment]
Hello, something like that: https://fakerjs.dev/api/science.html

**Comment by cieslarmichal** [comment]
Faker js docs are great resource to check while developing c++ faker 😃

**Comment by Shardul1908** [comment]
Ohh okay got it. Can you assign me this one as well?

**Comment by cieslarmichal** [comment]
Sure, done

**Comment by cieslarmichal** [comment]
hello, how is it going? will you work on this issue or should I unassign the issue?

**Comment by sharduld1908** [comment]
Hello I got my midterms coming up. Will work on this as soon as I get some time

**Comment by cieslarmichal** [comment]
Ok :)

**Comment by cieslarmichal** [comment]
Hey, assigned. We dont need sln files in repo, cmake generates them when building.
