### ISSUE TITLE
Add hacker module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#159]
Add a new module with following functionalities

- abbreviation
- adjective
- ingverb
- noun
- phrase
- verb

**Comment by eric-bodhi** [comment]
I can do this one. Would phrase be a grammatically correct pre-set phrase (already in a vector) or would it be a mix of all of the above say, adjective | noun | verb| 
And I'm assuming 'ingverb' refers to verbs like "running"?

**Comment by cieslarmichal** [comment]
Hey, sending helpful links to fakerjs:

https://github.com/faker-js/faker/blob/next/src/locales/en/hacker/phrase.ts

https://github.com/faker-js/faker/blob/next/src/locales/en/hacker/ingverb.ts

We would like to have the same thing basically.

**Comment by eric-bodhi** [comment]
Cool, I can do it.

**Comment by eric-bodhi** [comment]
#196
