### ISSUE TITLE
Add animal module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#160]
Add a new module with following functionalities

- bear
- bird
- cat
- cetacean
- cow
- crocodilia
- dog
- fish
- horse
- insect
- lion
- rabbit
- rodent
- snake
- type

**Comment by Globostofo** [comment]
Hello :)
I'll take this issue, can you assign me pls ?

I'll mostly take data from faker-js

**Comment by cieslarmichal** [comment]
Hello, sure, assigned :)
