### ISSUE TITLE
Add food module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#162]
Add a new module with following functionalities

- foodCategory
- grain
- milkProduct
- fruit
- meat
- seafood
- vegetable
- oil
- nut
- seeds
- sugarProducts
- non-alcoholic beverages
- alcoholic beverages
- dishName

**Comment by yakupcemilk** [comment]
Can I done this?

**Comment by cieslarmichal** [comment]
Hello! sure, I assiged you to this issue :)

**Comment by cieslarmichal** [comment]
hello, how is it going? will you work on this issue or should I unassign the issue?

**Comment by yakupcemilk** [comment]
I want to update, but it's not strictly necessary.

**Comment by cieslarmichal** [comment]
If you want to change something in code, go ahead and do another PR :)
