### ISSUE TITLE
Some tests can fail in date module

### ISSUE THREAD

**Issue by Globostofo** [cieslarmichal/faker-cxx#163]
Since the data in the tests is chosen **randomly**, it's possible for a test not to work every time, and for a bug to remain undiscovered if the tests are only run a few times.

The following test failed while I was coding other tests for issue #153:

```
[ RUN      ] DateTest.shouldGenerateBirthDateByRangeYear
/path/faker-cxx/src/modules/date/DateTest.cpp:150: Failure
Expected: (birthdate.tm_year + 1900) >= (1990), actual: 1989 vs 1990
```

In theory it's not my code that's causing it to fail, but I'm still investigating to be sure.

**Comment by Globostofo** [comment]
By spamming `make test` command, I've managed to find another test from the date module that sometimes fails:

```
[ RUN      ] DateTest.shouldGenerateBirthDateByExactYear
/home/plouc/faker-cxx/src/modules/date/DateTest.cpp:141: Failure
Expected equality of these values:
  birthdate.tm_year + 1900
    Which is: 1995
  1996
```

**Comment by cieslarmichal** [comment]
Ok thanks for investigating that, I will take a look.

**Comment by Globostofo** [comment]
I found the problem!

In [this function](https://github.com/cieslarmichal/faker-cxx/blob/d8a978d4ba28f5f1116b24767e16eb2021b17a84/src/modules/date/Date.cpp#L82C19-L82C34), the `tm_mday` attribute is set to 0 for the lower bound (line 87). However, a month starts on the 1st, so the lower bound is set to midnight on 31 December when it should be on 1 January at midnight.

Setting the variable to 1 definitely solves the problem. I'll do the PR.

**Comment by cieslarmichal** [comment]
Good job, I was also looking at the problem right now, and there was a problem with parsing ISO date in tests in parseISOFormattedStringToTm() and parseISOFormattedStringToTimePoint() functions, I fixed it: https://github.com/cieslarmichal/faker-cxx/pull/168. It took local time instead of UTC and shifted hours but we dont want that,

So we managed to find two bugs in there, nice :smile:

**Comment by cieslarmichal** [comment]
Marking as resolved
