### ISSUE TITLE
Docker run fail

### ISSUE THREAD

**Issue by Pe7o** [cieslarmichal/faker-cxx#171]
When running project via Docker (on win11 using CLion) for the first time, the process fails on command "cd build-linux-gxx" in "scripts/run_tests_linux_gxx.sh". 
Issue can be solved e.g. by running "chmod 777 build-linux-gxx" beforehand.

**Comment by cieslarmichal** [comment]
So if I uderstanding the issue correctly, is it enough to add chmod 777 inside the script, right?

**Comment by Pe7o** [comment]
Yes, exactly.

**Comment by cieslarmichal** [comment]
What you like to add this like? :)

**Comment by Pe7o** [comment]
Sure, would you assign me?

**Comment by cieslarmichal** [comment]
Assigned
