### ISSUE TITLE
Add barcode functionalities to Commerce module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#173]
Add  following functionalities:

- ean13
- ean8
- isbn10
- isbn13

**Comment by sebastianbacik** [comment]
Can you please assign this to me ? I pressume that the ean and isbn codes should be valid (with correct check digits).

**Comment by cieslarmichal** [comment]
Assigned, yes I think we should generate codes with valid check digit.

**Comment by cieslarmichal** [comment]
hello, how is it going? will you work on this issue or should I unassign the issue?

**Comment by sebastianbacik** [comment]
> hello, how is it going? will you work on this issue or should I unassign the issue?

Hi. I'm sorry for the delay, it will be done by the end of this week.

**Comment by cieslarmichal** [comment]
Sure, no problem :)
