### ISSUE TITLE
Add passport functionality to Person module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#181]
Add passport function with country to choose from Country enum as parameter, implement one of passport formats in generic way to be able to extend it to more countries.
Use city() function from Location module as a reference: https://github.com/cieslarmichal/faker-cxx/blob/main/include/faker-cxx/Location.h

**Comment by SidMalladi** [comment]
@cieslarmichal Hi, could you please assign this to me?

**Comment by cieslarmichal** [comment]
Hello, sure!

**Comment by cieslarmichal** [comment]
hello! how is it going? :)

**Comment by joshhn** [comment]
I can work on this @cieslarmichal.

**Comment by cieslarmichal** [comment]
assigned :)

**Comment by joshhn** [comment]
@cieslarmichal What should passport() return? Is it a passport number?

**Comment by cieslarmichal** [comment]
Yes :)
