### ISSUE TITLE
Add ssn functionality to Person module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#183]

**Comment by cieslarmichal** [comment]
@saharmyhre

**Comment by saharmyhre** [comment]
I'd like to work on this!

**Comment by cieslarmichal** [comment]
Ok, assigned :+1:

**Comment by cieslarmichal** [comment]
hello @saharmyhre, how is it going? :)

**Comment by saharmyhre** [comment]
hello @cieslarmichal, I got a new job and am in the middle of moving, if you would want to reassign the issue to someone else I am totally OK with that.
