### ISSUE TITLE
Add lch function to Color module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#189]

**Comment by saharmyhre** [comment]
Hi, I like to start working on this, can you give some more info about it? Thanks!

**Comment by cieslarmichal** [comment]
Hello, yes, please take a look at Color module, this function should be similar to hcl or rgb functions so it would retun "lch(l, c, h)" with values:
luminance: 0 to 100, chroma: 0 to 100, hue: 0 to 360. Hope it will help :)

**Comment by cieslarmichal** [comment]
I assigned you to this issue :rocket:
