### ISSUE TITLE
Add Medicine module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#193]
Add new module with following functionalities:

- specialty: [link](https://en.wikipedia.org/wiki/Medical_specialty)
- condition: [link](https://www.michigan.gov/-/media/Project/Websites/mdhhs/Folder2/Folder34/Folder1/Folder134/Medical_Conditions_and_Illnesses-Laminated.pdf?rev=0bf47ad5535241f3b4cb48d5aa039c45)
- medicalTest: [link](https://en.wikipedia.org/wiki/List_of_medical_tests)

**Comment by sandeshkhadka** [comment]
I am just implemented this, can you assign this to me and check my pr
