### ISSUE TITLE
Add Sport module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#194]
Add new module with following functionalities:

- sportName
- maleAthlete
- femaleAthlete
- soccerTeam
- sportEvent: (the most popular ones like World Cup, Olympic Games, NBA Finals) [link](https://bleacherreport.com/articles/562544-power-ranking-the-best-championships-in-sports)

**Comment by eric-bodhi** [comment]
I can do this one

**Comment by eric-bodhi** [comment]
#198
