### ISSUE TITLE
Extend fileExtension function from System module to have FileType enum argument

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#219]
File extension function should have enum argument FileType with values like Image, Text, Video and it will generate appropriate extension, for example if image is chosen it should generate one of ( apng",  "bmp",  "gif", "jpeg", "png", "svg+xml", "tiff","webp", "x-icon"). These extensions are already defined in types/MimeTypes.h but it need to be refactored.

**Comment by Goutham-AR** [comment]
#235
