### ISSUE TITLE
Add Image module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#220]
Add Image module with following functionalities:
- imageUrl (move from Internet module) - additionally change image provider to https://loremflickr.com/, example: https://loremflickr.com/640/480/nature, add enum category parameter with values [animals, business, cats, city, food, nightlife, fashion, people, nature, sports, technics, transport) and apply it to link like in the example above.
- githubAvatarUrl (move from Internet module)
- dimensions - should return image dimensions in format like "1920x1080"

**Comment by Kubaaa96** [comment]
Shouldn't the comment that is next to githubAvatarUrl be next to imageUrl? I don't see how loremflickr can be used to generate a GitHub avatar.

And also you can assign me to this

**Comment by cieslarmichal** [comment]
yes, you are right, I updated description :)
assigned
