### ISSUE TITLE
Add String guarantees

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#233]
Extend all functions from String module to support generation guarantees.
 Example1: generated string contains at least 1 ‘\’.
 Example2: generated string contains 1 ‘.’ and 1 ','. 
 Example3: generated string contains at least 3 ‘9’.

**Comment by cieslarmichal** [comment]
assigned @braw-lee

**Comment by cieslarmichal** [comment]
discussion https://github.com/cieslarmichal/faker-cxx/discussions/313

**Comment by braw-lee** [comment]
Please look at `String::alphanumeric()`.
It has a parameter : std::string& excludeCharacters, which is useless once we add string guarantee as users can just pass a char with atmost count as zero to the `GuaranteeMap` to ensure char is excluded.
So should I remove it while adding string guarantee overload or keep it as it is? @cieslarmichal

**Comment by cieslarmichal** [comment]
I think we could have it too, because it would be more intuitive for some users, just overload it :)

**Comment by cieslarmichal** [comment]
@braw-lee I have just added a new task with guarantees (for password) :)
https://github.com/cieslarmichal/faker-cxx/issues/352
