### ISSUE TITLE
Refactor String::uuid function

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#234]
Refactor uuid function from String module to not use static variables and have optional argument for your own random generator.

**Comment by Goutham-AR** [comment]
@cieslarmichal Should the distributions be included as parameters to the function or just the random number generator ?

**Comment by cieslarmichal** [comment]
It should be optional parameter and if no specified we should create ours.

**Comment by cieslarmichal** [comment]
Would you like to work on this issue?

**Comment by Goutham-AR** [comment]
> Would you like to work on this issue? 

Yes.

**Comment by cieslarmichal** [comment]
Ok, assigned :)
