### ISSUE TITLE
Add bio function to Person module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#239]
https://github.com/faker-js/faker/blob/c2b952347e1f952cf379807a3c456fed65075d11/src/locales/en/person/bio_pattern.ts#L4

https://github.com/faker-js/faker/tree/c2b952347e1f952cf379807a3c456fed65075d11/src/locales/en/person

**Comment by MikelKokoshi** [comment]
Hi i would like to work on this, can you assign it to me?

**Comment by cieslarmichal** [comment]
Sure, assigned :)
