### ISSUE TITLE
Add Crypto module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#245]
Add Crypto module with following functionalities:

-md5 (optional data arg, if not provided hash randomized data)
-sha256 (optional data arg, if not provided hash randomized data)

**Comment by SunHashira** [comment]
Hi, if I understand correctly, you want to hash data which is supposed to be some string or something else ? If so, is using openssl/md5.h and sha.h okay ? And if data are not provided, is hashing generated random word with Word.h enough to get needed hash ?

**Comment by cieslarmichal** [comment]
Hello, if data is not provided, some words are fine. I would like to avoid additional libs dependecies so maybe we could copy those algorithms from internet to our codebase? What do you think?

**Comment by SunHashira** [comment]
I don't think it will be a problem to find some algorithms and use them but, I'm not proficient with copyright so I'm not exactly sure where to find freely available ones.

**Comment by cieslarmichal** [comment]
Here it is:

https://github.com/flexxxxer/md5_hash

https://github.com/System-Glitch/SHA256

Please add file ExternalLicenses.txt and copy their LICENSE file contents into it like:

External repositories licenses:

1. flexxxxer/md5_hash:

license...

2. System-Glitch/SHA256:

license...

**Comment by SunHashira** [comment]
Okay, thanks for help, you can assign me this module and im going to do it now. Dumb question but just to be clear, ExternalLicenses.txt should be in module crypto folder ?

**Comment by cieslarmichal** [comment]
Assigned. In project root so we can add all future external licenses there
