### ISSUE TITLE
Add sql generation to Database module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#247]

**Comment by MikelKokoshi** [comment]
Assign it to me, please.

**Comment by cieslarmichal** [comment]
ok

**Comment by sdorbala** [comment]
@cieslarmichal - Is there any progress made for this issue? If this needs to be tackled, I can give it a try. Can we get more clarity on what needs to be done? Is the ask to generate SQL statements (guessing data insertion scripts) for various engines involved here?

**Comment by cieslarmichal** [comment]
I think you can work on this :)

Basically you can create a sqlCommand function that takes one enum parameter to choose which type of command to use

```
These SQL commands are mainly categorized into five categories:
DDL – Data Definition Language.
DQL – Data Query Language.
DML – Data Manipulation Language.
DCL – Data Control Language.
TCL – Transaction Control Language.
```

So given query param you could generate something like `SELECT email, name from users`; where users and table columns can be randomized from some array, also there can be some chances to limit or offset appended to the end of query.

Given manipulation param it would be something like `INSERT into users (id, name, email) VALUES ('id', 'name', 'email@gmail.com');`

Similar to that you can do other commands like update, delete, grant, revoke etc.

Hope it helps, good luck!

**Comment by sdorbala** [comment]
https://github.com/cieslarmichal/faker-cxx/pull/532
