### ISSUE TITLE
Add multilanguage sexes

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#251]
Add support for sexes (Male, Female) in multiple langauges.
example in Poland: (Mężczyzna, Kobieta)

**Comment by qmohitsingh** [comment]
hey @cieslarmichal , could you please assign this issue to me? Thank you

**Comment by cieslarmichal** [comment]
Hello! sure, assigned, please give a star to the repository to make this project more popular 🔥
