### ISSUE TITLE
Wrong code documentation and possibly non usable function

### ISSUE THREAD

**Issue by braw-lee** [cieslarmichal/faker-cxx#274]
file : include/faker-cxx/String.h
`
/**
     * @brief Returns shuffled STL container.
     *
     * @tparam T an element type of the container.
     *
     * @param data The container.
     *
     * @return Container with shuffled elements.
     *
     * @code
     * Helper::arrayElement<char>(std::string{"abcd"}) // "dcba"
     * @endcode
     */

    template <class T>
    static std::vector<T> shuffle(std::vector<T> data)
    {
        std::shuffle(std::begin(data), std::end(data), pseudoRandomGenerator);
        return data;
    }
`
Code example should be of Helper::shuffle() 
Also I don't think we can pass a string to the shuffle function, no viable conversion from std::string to std::vector<char>

**Comment by cieslarmichal** [comment]
Thanks for creating the issue :)

**Comment by cieslarmichal** [comment]
https://github.com/cieslarmichal/faker-cxx/pull/275
