### ISSUE TITLE
GitTest Conversion Warning/Error Using msys/g++ on Windows

### ISSUE THREAD

**Issue by capo-at-the-5th-fret** [cieslarmichal/faker-cxx#285]
The message:

X:\Desktop\cloneyard\faker-cxx\src\modules\git\GitTest.cpp: In member function 'virtual void GitTest_shouldGenerateBranch_Test::TestBody()':
[build] X:\Desktop\cloneyard\faker-cxx\src\modules\git\GitTest.cpp:42:77: error: conversion from 'std::vector<std::__cxx11::basic_string<char> >::size_type' {aka 'long long unsigned int'} to 'long unsigned int' may change value [-Werror=conversion]
[build]    42 |     unsigned long branchSplit = faker::StringHelper::split(branch, "-").size();

I changed the branchSplit type to const auto and it worked fine. (compiled + all tests passed)

**Comment by cieslarmichal** [comment]
Hello thanks for creating the issue :) Could you submit a PR for it?
