### ISSUE TITLE
Add people names from Bulgaria

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#303]

**Comment by Duggi-Niharika-Sai-06** [comment]
Hello,

I came across this issue labeled as  in your repository, and I'm very interested in contributing to it as part of a school project.

I believe working on this issue will not only help me gain practical experience in, but also contribute positively to your project. I've reviewed the contribution guidelines for your repository and am ready to adhere to them.

Could you please let me know if it's possible for me to work on this issue? If there are any specific requirements or starting points you'd like me to know, I'd be glad to hear them.

Thank you for considering my request. I'm looking forward to the opportunity to contribute to your project.

Best regards,
Neethu Duggi

**Comment by cieslarmichal** [comment]
Hello!

I am happy you are going to join faker's contributors :)
I have just assigned you this issue, feel free to work on that.

Here is my commit with adding people names: https://github.com/cieslarmichal/faker-cxx/commit/8b0c514a25252e4516e02d5157613148e793bea7 - you can take that as a reference.
We have a discord server for contributors: https://discord.gg/eKcH3nTf - you can join if you are interested in some discussion or even just for community.
Dont forget to give a star to the project to make it more popular :rocket: 

Best regards,
Michał

**Comment by Duggi-Niharika-Sai-06** [comment]
thank you for assigning this issue to me!
