### ISSUE TITLE
change fmt lib to be a dependency only if compiler is apple clang++

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#349]
For windows and linux codebase should use std::format, for apple clang++ it should use fmt::format.
Fmt library also should not be downloaded if compiler for compilers other than apple clang++.

**Comment by eric-bodhi** [comment]
I've done a lot on the discord so I might as well be assigned to it

**Comment by cieslarmichal** [comment]
Assigned
