### ISSUE TITLE
Add timestamps to Date API

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#382]
add new parameter to all date module functions like `bool timestamp` with default value false that enables returning date with timestamp format instead of ISO

**Comment by eric-bodhi** [comment]
Hello, I'll do this one. Haven't worked in C++ in a while so we'll see how it goes. I'll return an object with the ISO and timestamp formats. For testing I suppose since everything is in ISO i'll have to make it test timestamp as well

**Comment by cieslarmichal** [comment]
Ok, assigned, good luck!

**Comment by eric-bodhi** [comment]
oops didnt mean to unassign that, dont click a button thinking it will ask you if you really want to do that

**Comment by cieslarmichal** [comment]
How is it going?
