### ISSUE TITLE
Add location addresses data from Palestine 

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#458]

**Comment by layasri157** [comment]
please assign it to me

**Comment by cieslarmichal** [comment]
Assigned

**Comment by charan-003** [comment]
i want to work on it

**Comment by cieslarmichal** [comment]
Assigned

**Comment by charan-003** [comment]
just want to confirm, this is to be done in location_data.cpp right

**Comment by cieslarmichal** [comment]
Yes and it to switch statement like any other location data in location.cpp and location_test.cpp and add test for it
