### ISSUE TITLE
Add location addresses data from Israel 

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#459]

**Comment by SayeedKhan21** [comment]
hey @cieslarmichal I think as a first contribution I will start with this issue . I just wanted to ask how do fetch all the cities, states, prefixes accurately ? Like is there any specific web site through which gather all this info ?

**Comment by cieslarmichal** [comment]
Hello, here you go:
https://github.com/faker-js/faker/tree/next/src/locales/he/location

**Comment by cieslarmichal** [comment]
Consider giving a star to the repository to make this project more popular 🌟

**Comment by SayeedKhan21** [comment]
hey @cieslarmichal could you tell me what do these folders mean ? Like what does the "he" folder here contain ?

**Comment by cieslarmichal** [comment]
He is for hebrew language - Israel. It contains all location data needed here.

**Comment by SayeedKhan21** [comment]
do u have a reference of the same as well ?  Like you mentioned he is for hebrew , similarly other folders also mean something or the other , so u like do have a file containing all such stuff/mappings ? It would be great in that case

**Comment by cieslarmichal** [comment]
In fakerjs in each folder there is a metadata file which contains info which country and language it s about, but I am now aware of general mapping for list of countries

**Comment by SayeedKhan21** [comment]
@cieslarmichal what files are expected in israel folder in /location/data/israel ? Israelcities , Israelstates and ?  . Should i take up all the related files in fakerjs he folder ? https://github.com/faker-js/faker/tree/next/src/locales/he/location

**Comment by cieslarmichal** [comment]
Look for example in https://github.com/cieslarmichal/faker-cxx/tree/main/src/modules/location/data/poland
and add corresponding definitions but for Israel.

**Comment by SayeedKhan21** [comment]
@cieslarmichal Vscode is not rendering the hebrew names properly on my system . I actually wanted to add double quotes to all names as per done in all the files and while doing so I realized that  some of the names are not getting rendered properly . Any suggestions on this ?

**Comment by cieslarmichal** [comment]
Yes, what file encoding do you have in your file? It should be utf8 as I remember

**Comment by SayeedKhan21** [comment]
Its UTF-8 itself . How do you double quote entire ts file  ? Any specific method that u use ?

**Comment by cieslarmichal** [comment]
I dont uderstand it I guess, could you give me more detailed explaination? With examples etc

**Comment by SayeedKhan21** [comment]
Can i dm you on discord ?

**Comment by cieslarmichal** [comment]
Sure

**Comment by cieslarmichal** [comment]
Sure go ahead! Assigned
