### ISSUE TITLE
Add creditCardType function in Finance module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#478]
visa etc values

**Comment by jessleathe** [comment]
done

**Comment by cieslarmichal** [comment]
hey, please change the implementation as I requested changes:
method should be like 
```std::string creditCardType() {
//return "visa" "masterCard" etc
}

**Comment by cieslarmichal** [comment]
no additional logic, just random string :)

**Comment by sdorbala** [comment]
@cieslarmichal - I can continue the work for this issue. Do you want to assign this to me?

**Comment by sdorbala** [comment]
Created a PR to fix this issue. #520
