### ISSUE TITLE
Add product related new functionalites in Commerce module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#480]
- productDescription
- productCategory (furnitures, cars etc)
- productReview
- productRating (0-5)

**Comment by PlungedInCode** [comment]
Assign it to me pls

Also it would be great if you provide more information about this functions

**Comment by cieslarmichal** [comment]
Description could be like: "brand new" or "used", "bear traces of use" etc you can be creative here :)
Category - string one of values of cars, furnitures, food, devices etc google some list of product categories
Review: we can prepare some array of example reviews like : "I am satisfied with this purchase", "I bought it couple days ago and it meets my expectations," like 20 of sentences like that also megative ones and one random sentence from it, also a chance to be creative 😁
