### ISSUE TITLE
Add payment related new functionalites in Commerce module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#483]
- paymentId
- paymentType (credit card | money transfer | cash etc)
- paymentProvider (stripe | paypal etc)

**Comment by srivastava-yash** [comment]
I could work on this. 
I have one question about paymentId, if we are expecting a random number or like a random alpha-numeric string?

**Comment by cieslarmichal** [comment]
It can be uuid from String module

**Comment by cieslarmichal** [comment]
Consider giving a star to the repository to make the project more popular 😎
