### ISSUE TITLE
Add new functionalities to Date module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#489]
Add functions:

- year (returns unsigned int like 1996)
- month (returns unsigned int, 1-12)
- hour
- minutes
- seconds
-  time (example "11:25")
- dayOfMonth (returns unsigned int 1-31)
- dayOfWeek (returns unsgined int 1-7)
- timezone (returns random timezone)

**Comment by NateClarke0** [comment]
Hello, may I work on this issue? I really want to get hands-on experience working with open source software and this would be my first contribution.

I just have a few quick questions. 

For the hour function, should a random integer between 1 and 12 (or 0 and 23) be returned?
For the minutes and seconds functions, should they return integers between 0 and 59 like in time?

**Comment by cieslarmichal** [comment]
Hello, sure, go head. I assigned you to thia issue.
Hour 0-23, minutes, seconds 0-59

**Comment by cieslarmichal** [comment]
Go ahead :)

**Comment by sdorbala** [comment]
A couple of questions. 
1. Should the date be accurate? As in, it shouldn't return Nov 31 2024 as this will be invalid.
2. Should the date be leap year aware? Feb 29 2024 is valid but Feb 29 2023 will be invalid etc?

**Comment by sdorbala** [comment]
Any lower/upper limit for the year?

**Comment by cieslarmichal** [comment]
Lets do 1950 - 2050
