### ISSUE TITLE
Add author function to Git module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#490]
author(): Generates a random Git author name and email.

**Comment by srivastava-yash** [comment]
I could pick this. Could you assign it to me?

**Comment by cieslarmichal** [comment]
Yea go ahead :)

**Comment by srivastava-yash** [comment]
Somehow the PR is not getting linked here. [https://github.com/cieslarmichal/faker-cxx/pull/498]
