### ISSUE TITLE
ipv4 support

### ISSUE THREAD

**Issue by KacperWojciechowski** [cieslarmichal/faker-cxx#52]
Add following API for the IPv4 generation support:

- generation based on mask: Internet::ipv4(unsigned char mask, std::optional<std::array<char, 4>>maskedIp = std::nullopt)
- generation based on IP class: Internet::ipv4(Internet::IPv4 class = Internet::IPv4::classC)

**Comment by cieslarmichal** [comment]
https://github.com/cieslarmichal/faker-cxx/pull/66
