### ISSUE TITLE
suggestion: Add support for external libfmt and google test

### ISSUE THREAD

**Issue by uilianries** [cieslarmichal/faker-cxx#546]
Hello, as we are packaging Faker CXX on Conan (PR https://github.com/conan-io/conan-center-index/pull/24018), we actually use external CMake targets for fmt and GTest, instead of consuming the vendorized one in the externals folder.

GTest is officially adopted in CMake and can be included directly:

- https://cmake.org/cmake/help/latest/module/GoogleTest.html

The fmt library has its own CMake support: 

- https://github.com/fmtlib/fmt/blob/master/CMakeLists.txt#L408

So the idea would be including a new option like `USE_SYSTEM_DEPENDENCIES`, then load all dependencies with `find_package` and linking to their CMake targets.

I could open a PR with the feature in case acceptable.

**Comment by cieslarmichal** [comment]
I think it is a good idea, go ahead 👍 

If you have any more suggestions/ideas I am more than open to hear about possible improvements.
