### ISSUE TITLE
refactor science module data

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#575]
Move all module data into <ModuleName>Data.h and <ModuleName>Data.cpp next to <ModuleName>.cpp, use std::array, std::string_view, std::unordered_map for data definitions, reference Airline module data.

**Comment by justinlopez1** [comment]
Can I take a stab at this this weekend? Its my first time contributing to open source and i am still relatively new to git, but I'll be able to do it. Thanks

**Comment by cieslarmichal** [comment]
sure, assigned :) if you need any help join our discord community! :smile: also don't forget to give a star to the project :star:
