### ISSUE TITLE
refactor system module data

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#578]
Move all module data into <ModuleName>Data.h and <ModuleName>Data.cpp next to <ModuleName>.cpp, use std::array, std::string_view, std::unordered_map for data definitions, reference Airline module data.

**Comment by ishan-tyagi** [comment]
I'd like to take on this issue. It's my first time contributing to open source, but I'd like to give it a shot.

**Comment by cieslarmichal** [comment]
Ok, assigned :) consider giving a star to the project 👍

**Comment by cieslarmichal** [comment]
any progress yet?

**Comment by ishan-tyagi** [comment]
I've refactored the code, but I'm running into issues trying to get the existing functions to work with the string_view data. I'm still working on it, hopefully it will be done before the end of this week.

**Comment by cieslarmichal** [comment]
done
