### ISSUE TITLE
refactor word module data

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#582]
Move all module data into <ModuleName>Data.h and <ModuleName>Data.cpp next to <ModuleName>.cpp, use std::array, std::string_view, std::unordered_map for data definitions, reference Airline module data.

**Comment by ruxixa** [comment]
I want to work on this one .I'm going to start today

**Comment by cieslarmichal** [comment]
ok, assigned

**Comment by cieslarmichal** [comment]
any progress on it?

**Comment by eric-bodhi** [comment]
I hope he won't mind but he hasn't done anything in a while, if possible I'd like to be assigned

**Comment by cieslarmichal** [comment]
Sure, go ahead

**Comment by cieslarmichal** [comment]
assigned

**Comment by eric-bodhi** [comment]
Oh someone else already did it while I was sleeping, bravo.

**Comment by cieslarmichal** [comment]
@eric-bodhi data still needs to be moved to one file - WordData as other modules, so you can work on that.

**Comment by cieslarmichal** [comment]
if not I can do it
