### ISSUE TITLE
fix codecov

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#598]
Code coverage is currently somehow broken and only shows code coverage in tests files, not in source files.

**Comment by cieslarmichal** [comment]
probably tests directory cmakelists should be included in main cmakelists before sources in the beginning of the file (not in the end)

**Comment by uilianries** [comment]
I can take a look in this one. I used to use codecov in past projects. Now with Github marketplace and app integration, it's much straightforward than before.

**Comment by cieslarmichal** [comment]
I was doing little investigation in my past projects that have codecov working well and I see the difference that in here we link from fakerUT to faker and back then I added sources with ut sources to UT executable definition. Maybe it will be helpful

**Comment by cieslarmichal** [comment]
I merged PR and set token env but it outputs some error:

```
==> Running command '/home/runner/work/_actions/codecov/codecov-action/v4.0.1/dist/codecov do-upload'
/home/runner/work/_actions/codecov/codecov-action/v4.0.1/dist/codecov do-upload
info - 2024-07-02 22:35:52,721 -- ci service found: github-actions
warning - 2024-07-02 22:35:52,731 -- xcrun is not installed or can't be found.
warning - 2024-07-02 22:35:52,754 -- No gcov data found.
warning - 2024-07-02 22:35:52,755 -- coverage.py is not installed or can't be found.
info - 2024-07-02 22:35:52,806 -- Found 0 coverage files to report
Error: No coverage reports found. Please make sure you're generating reports successfully.
```

**Comment by cieslarmichal** [comment]
https://github.com/cieslarmichal/faker-cxx/actions/runs/9768106735/job/26967220836

**Comment by uilianries** [comment]
@cieslarmichal I didn't see the coverage step in clang build 😞 

Anyway, I removed it on this new PR #776. Still, we are running and is working on static analysis build.

Also, you have to configure the codecov token, the CI reported that's missing: https://github.com/cieslarmichal/faker-cxx/actions/runs/9768106754/job/26964867122#step:13:34

The instructions to add the token are listed here: https://app.codecov.io/gh/cieslarmichal/faker-cxx/settings

**Comment by cieslarmichal** [comment]
I added CODECOV_TOKEN secret so I don't know why it doesnt find it, will check it later

**Comment by cieslarmichal** [comment]
I think it works now: https://app.codecov.io/github/cieslarmichal/faker-cxx
