### ISSUE TITLE
add script for running clang format

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#614]

**Comment by cieslarmichal** [comment]
hey, so we have a .clang-format config we should use for formatting our code, people tend not to use it because they don't know how (maybe other reason)

we would like to create a script that invokes clang-format executable and takes all the project files and format them with that config :)

**Comment by cieslarmichal** [comment]
do you want to work on this?

**Comment by pixelcaliber** [comment]
@cieslarmichal  yes, could you please assign this to me?

**Comment by cieslarmichal** [comment]
Assigned

**Comment by pixelcaliber** [comment]
hey @cieslarmichal I've tried creating a script with command-line arguments, is this what we are planning to add?

**Comment by cieslarmichal** [comment]
the bash script will do

**Comment by cieslarmichal** [comment]
something like `clang-format src/**/*.cpp src/**/*.h include/**/*.h -i -style=file`
