### ISSUE TITLE
enhancement: Use cache feature in CI to avoid rebuilding dependencies

### ISSUE THREAD

**Issue by uilianries** [cieslarmichal/faker-cxx#624]
The Github Actions can be combined with a cache step to store folder and recover then in next build:

https://github.com/marketplace/actions/cache

As we are using submodules for external dependencies and Conan, it takes few minutes to build for every new CI push. It would be great if we could save that time by restoring cached binaries instead.

**Comment by cieslarmichal** [comment]
Good idea
