### ISSUE TITLE
improve guides for contributors

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#629]

**Comment by cieslarmichal** [comment]
```
cmake -B ./build -DCMAKE_CXX_COMPILER=clang++ -DBUILD_TESTING=ON

cmake --build ./build

ctest --test-dir ./build
```

**Comment by justinlopez1** [comment]
1) Add Compiler and CMake and Ninja to PATH

2) cmake -B ./build -DCMAKE_CXX_COMPILER=clang++ -DBUILD_TESTING=ON (I used g++ there and it also worked fine)

3) cmake --build ./build

4) build\tests\Debug\faker-cxx-UT.exe (just running the executable there ran the test cases, the command in the comment above was giving me an error)
