### ISSUE TITLE
add plant module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#633]
Add new module with at least two functions (or more):

- flower()
- tree()

**Comment by jonah-d22** [comment]
I'd like to try helping with this issue. I'm assuming this issue will also want the tests created? Also is there a list of data that will be used or is getting that data part of this issue as well?

**Comment by cieslarmichal** [comment]
All features have tests so that goes without saying :) I don't have any data here, you need to google it 😅

**Comment by cieslarmichal** [comment]
Also, consider giving a star to the repository to make this project more popular ⭐💪

**Comment by cieslarmichal** [comment]
good job with code - could you add plant module to project README? (we have a list of modules there)
