### ISSUE TITLE
Support for bzlmod

### ISSUE THREAD

**Issue by meftunca** [cieslarmichal/faker-cxx#646]
Please provide support so that Bazel users can easily use your project with bzlmod. 

https://bazel.build/external/overview#bzlmod

After integration, it will appear as accessible as in the link below.
https://registry.bazel.build/all-modules

**Comment by cieslarmichal** [comment]
Hello! thanks for creating the issue, we will implement it :)

**Comment by meftunca** [comment]
@cieslarmichal You are a great team, thank you :)

**Comment by meftunca** [comment]
Any progress on the project? @cieslarmichal

**Comment by cieslarmichal** [comment]
I started learning about BAZEL, I think I will start configuring it this week.

**Comment by cieslarmichal** [comment]
https://github.com/cieslarmichal/faker-cxx/pull/760
