### ISSUE TITLE
fix clang tidy errors

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#654]
https://github.com/cieslarmichal/faker-cxx/actions/runs/9528652077/job/26266591173

**Comment by 00thirdeye00** [comment]
can you give some more information about this issue?

**Comment by cieslarmichal** [comment]
When running clang-tidy it gives a lot of errors, I am not familiar with clang tidy much but it's static analysis of the code,
It would improve our code quality. First we can add clang tidy config, for example [ref](https://github.com/nlohmann/json/blob/develop/.clang-tidy) its also issue for that: https://github.com/cieslarmichal/faker-cxx/issues/617

**Comment by cieslarmichal** [comment]
and clang tidy runs in continous integration with github workflow but it's turned off so it doesn't fail - running but fails does not fail entire pipelines

**Comment by 00thirdeye00** [comment]
> and clang tidy runs in continous integration with github workflow but it's turned off so it doesn't fail - running but fails does not fail entire pipelines

unclear?

**Comment by cieslarmichal** [comment]
check the pipeline output I added in issue description, there are errors that need to be resolved, for now we skip them

**Comment by 00thirdeye00** [comment]
also there is a warning about [implicit conversion](https://github.com/cieslarmichal/faker-cxx/actions/runs/9528652077/job/26266591173#step:5:289). how about typecasting float to double or viceversa at [these](https://github.com/cieslarmichal/faker-cxx/blob/f36227ace30678563164d695097688c461032b48/src/modules/datatype/Datatype.cpp#L20) comparisons?

**Comment by cieslarmichal** [comment]
Yes we should fix that

**Comment by jackhwalters** [comment]
I can take this up.

**Comment by cieslarmichal** [comment]
Ok assigned

**Comment by cieslarmichal** [comment]
do you consider adding some clang-tidy config?
https://github.com/cieslarmichal/faker-cxx/issues/617

**Comment by jackhwalters** [comment]
Struggling to get this working, seems like you need to add `set(CMAKE_CXX_USE_RESPONSE_FILE_FOR_INCLUDES Off)` to CMakeLists and change build options. I think you're better placed to work that out than me so can you unassign me.

**Comment by jackhwalters** [comment]
I think you're better placed to solve this @cieslarmichal than me, will require a better understanding of build processes. Have unassigned myself. See [here](https://stackoverflow.com/questions/39455090/clang-tidy-cant-find-my-header-files/39596822#39596822) for more info.
