### ISSUE TITLE
change file names to match google file names convention

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#713]
[file naming convention](https://google.github.io/styleguide/cppguide.html#File_Names)

**Comment by cieslarmichal** [comment]
I prefer camelCase but its not cpp standard I think

**Comment by cieslarmichal** [comment]
So dashes or underscores, we can decide later

**Comment by cieslarmichal** [comment]
we can go with undescores

**Comment by 00thirdeye00** [comment]
So we modify names for all the files?

**Comment by cieslarmichal** [comment]
yup

**Comment by 00thirdeye00** [comment]
@cieslarmichal I just to make sure, is it only .c and .h files or every file name in the project src?

**Comment by cieslarmichal** [comment]
Its good
