### ISSUE TITLE
System feature 

### ISSUE THREAD

**Issue by shekeraoleksandr** [cieslarmichal/faker-cxx#72]
Gonna implement:
- commonFileExtension
- commonFileName
- commonFileType
- cron
- directoryPath
- fileExtension
- fileName
- filePath
- fileType
- mimeType
- networkInterface
-  and maybe semanticVersion

**Comment by cieslarmichal** [comment]
Would you like to join contributors discord channel? :) or you prefer to work without it?

**Comment by shekeraoleksandr** [comment]
> Would you like to join contributors discord channel? :) or you prefer to work without it?

I'm already in it :)

**Comment by cieslarmichal** [comment]
https://github.com/cieslarmichal/faker-cxx/pull/73
