### ISSUE TITLE
add article on dev.to with faker example

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#725]

**Comment by uilianries** [comment]
I could write the post 😄 Of course, I would shared the draft first to have your review/changes/approval.

**Comment by cieslarmichal** [comment]
Ok :smile: let me know when you will have a draft :fire:

**Comment by uilianries** [comment]
@cieslarmichal Please, take a look in https://gist.github.com/uilianries/1ec377525eed5474d29c687adf49e622

**Comment by cieslarmichal** [comment]
it's cool!! nice image with faker logo 👍 
I would add github submodule as alternative to conan for consuming package

**Comment by cieslarmichal** [comment]
I think we could add this `Key Features` section to our main readme as well :D very nice

**Comment by uilianries** [comment]
>  I would add github submodule as alternative to conan for consuming package

Okay, I'll update it 😄

**Comment by uilianries** [comment]
@cieslarmichal I just updated the post, please, take a look in https://gist.github.com/uilianries/1ec377525eed5474d29c687adf49e622#file-post-md

**Comment by cieslarmichal** [comment]
Looks good 🚢

**Comment by cieslarmichal** [comment]
do you think it's a good idea to add the introduction and key features sections to our readme? they seem fresh

**Comment by uilianries** [comment]
Yes, I do, because usually people want to know if worth using or not a library. The introduction would clarify that.

**Comment by cieslarmichal** [comment]
Ok lets do that

**Comment by uilianries** [comment]
Published on dev.to: https://dev.to/uilianries/faker-c-generate-realistic-fake-data-for-testing-and-development-2eh2

**Comment by cieslarmichal** [comment]
Perfect! 😎

**Comment by cieslarmichal** [comment]
I added introduction to readme :)
