### ISSUE TITLE
add one header faker.h to expose all faker modules functionalities

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#734]

**Comment by alejandronespereira** [comment]
Hi can I take this one?

**Comment by cieslarmichal** [comment]
yup, assigned

**Comment by cieslarmichal** [comment]
consider giving a star to the repository to make this project more popular :star:

**Comment by alejandronespereira** [comment]
What tests would you like here? I am thinking about adding one struct/class of each .h file as that is enough to check the .h is pulling all the data structures and not to bloat too much the testing file, WDYT?

**Comment by cieslarmichal** [comment]
I dont think tests are needed here, just create one file and include all other headers, this way one can use all modules without knowing what are their names, but there will be still a possibility to include what you use :)
