### ISSUE TITLE
migrate StringHelper class to namespace common

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#755]

**Comment by 00thirdeye00** [comment]
Hej, if no one is working on this, I can take this

**Comment by cieslarmichal** [comment]
ok, assigned

**Comment by cieslarmichal** [comment]
it would be `common` namespace

**Comment by 00thirdeye00** [comment]
Hej @cieslarmichal is it going to be `common::StringHelper::` or just `common::` without module name?

**Comment by cieslarmichal** [comment]
Hey @00thirdeye00 just common
