### ISSUE TITLE
ci: Cache static-analysis clang-tidy build to save CI time

### ISSUE THREAD

**Issue by uilianries** [cieslarmichal/faker-cxx#764]
In order to run Clang tidy, we need first build the project. This operation cost time, usually 1 or 2 minutes, but will be higher as the project is bigger and bigger.

To save time, we could cache the build folder and re-use it on next PR execution, same as we have been used for mac, linux and windows build. The result should be only few seconds in a second rounds, only build changed files and linking library again.

**Comment by cieslarmichal** [comment]
I don't think it's important for now, maybe in future
