### ISSUE TITLE
create e-sport module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#768]
add new module with following methods:

 - std::string_view player();
 - std::string_view team();
 - std::string_view league();
 - std::string_view event();
 - std::string_view game();

**Comment by dubloom** [comment]
Hi ! I'm trying to contribute to open source projects and I'd like to take care of this issue if possible please !

**Comment by cieslarmichal** [comment]
Hello, ok go ahead, assigned :)

**Comment by cieslarmichal** [comment]
Consider giving a star to the repository to make this project more popular 😎
