### ISSUE TITLE
create video module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#770]
new module with following methods:

- formatName 
- fileExtension
- videoCodec
- audioCodec
- resolution (1920x1080 etc)
- aspectRatio
- videoUrl (something like we do for images to generate random url to existing video) its optional as I don't know if something like that exists

ref: https://en.wikipedia.org/wiki/Video_file_format

**Comment by dubloom** [comment]
Hey, if you are happy with my pull requests about esport module, i can deal with this module too

**Comment by cieslarmichal** [comment]
Good PR, happy about it, go ahead and take the next one 👍

**Comment by dubloom** [comment]
About the video url thing. Would an array of youtube video be a good solution ?

**Comment by cieslarmichal** [comment]
I think its fine approach
