### ISSUE TITLE
add missing tests for Git

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#784]
https://app.codecov.io/github/cieslarmichal/faker-cxx/blob/main/src%2Fmodules%2Fgit%2FGit.cpp

**Comment by 00thirdeye00** [comment]
this is not because of arguments to the functions, the failed cases are because of hardcoding in .cpp file. Please have a look and suggest.

**Comment by 00thirdeye00** [comment]
I think this issue is closed.
