### ISSUE TITLE
add missing tests for person module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#810]
https://app.codecov.io/github/cieslarmichal/faker-cxx/blob/main/src%2Fmodules%2Fperson%2Fperson.cpp

**Comment by hussein-mamane** [comment]
hello, I would like to test the modules (probably not all of them), can you explain exactly what to test in them, how to proceed and the tool you want to use , maybe just test one of the modules to show how you want it done. I think it is repetitive, so I can follow your example test. It would be nice to explain your issues so I can onboard in, I am new to OpenSource .
Thanks

**Comment by cieslarmichal** [comment]
Take a look at person source code person.cpp and person_test.cpp and then visit a link I sent, it shows covered lines with tests, so the job will be to cover lines that are red (not covered) - write additional tests in person_test file

**Comment by cieslarmichal** [comment]
If you have any questions related to setup join our discord channel (link in readme)

**Comment by hussein-mamane** [comment]
thanks

**Comment by cieslarmichal** [comment]
consider giving a star to the repository to make this project more popular :star:

**Comment by hussein-mamane** [comment]
hello, can you unassign the person.cpp test from me. I am not ready now, I am looking at the code.

**Comment by cieslarmichal** [comment]
Ok
