### ISSUE TITLE
add missing tests for word module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#813]
https://app.codecov.io/github/cieslarmichal/faker-cxx/blob/main/src%2Fmodules%2Fword%2Fword.cpp

https://app.codecov.io/github/cieslarmichal/faker-cxx/blob/main/src%2Fmodules%2Fword%2Fword_data.h

**Comment by jackhwalters** [comment]
I can take this up.

**Comment by cieslarmichal** [comment]
Ok assigned
