### ISSUE TITLE
use standard function to check if the number is nan()

### ISSUE THREAD

**Issue by 00thirdeye00** [cieslarmichal/faker-cxx#815]
https://github.com/cieslarmichal/faker-cxx/blob/540cea831c11b5680454a148276388fd5e201a84/src/modules/datatype/datatype.cpp#L16

this line will always be true. instead it might be better if we use standard library function to check if a number is `nan` using `isnan(x)`

_Originally posted by @00thirdeye00 in https://github.com/cieslarmichal/faker-cxx/discussions/814_

**Comment by eric-bodhi** [comment]
https://github.com/cieslarmichal/faker-cxx/pull/837
