### ISSUE TITLE
Missing #include<string> MSVC

### ISSUE THREAD

**Issue by julianfritzsch** [cieslarmichal/faker-cxx#851]
When trying to build the project using the MSVC compiler version 19.41.34120.0 the build fails with a whole bunch of errors of the type
`faker-cxx\include\faker-cxx\airline.h(89,23): error C2039: 'string': is not a member of 'std'
 [C:\Users\\Documents\faker-cxx\build\faker-cxx.vcxproj]
  (compiling source file '../src/modules/airline.cpp')
      C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\include\__msvc_string_view.hpp
  (22,1):
      see declaration of 'std'`
This happens for all files that only include `string_view` but use `std::string`. Including `string` solves the problem and the library builds.

**Comment by cieslarmichal** [comment]
hello, thanks for reporting the issue! 👍 would you like to work on this or should someone else fix it? 🙂
