### ISSUE TITLE
fix branchWithoutIssueNumTest flaky test

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#867]
this test sometimes fails, need to investigate and fix

**Comment by 00thirdeye00** [comment]
any notes or error log on this?

**Comment by cieslarmichal** [comment]
no I dont have much but I saw couple times in PR run it failed, once locally, probably we could run this test several times and check how it behaves

**Comment by cieslarmichal** [comment]
https://github.com/cieslarmichal/faker-cxx/actions/runs/10496062791/job/29075874684#step:11:3895

**Comment by 00thirdeye00** [comment]
I ran tests several times locally while printing to console
```
generatedNoun: e
/home/combine/projects/faker-cxx/tests/modules/git_test.cpp:99: Failure
Value of: std::ranges::any_of(word::nouns, [generatedNoun](const std::string_view& word) { return word == generatedNoun; })
  Actual: false
Expected: true
```
it prints a character `e` for nouns

**Comment by 00thirdeye00** [comment]
I think we must not have words like `warm-up` this in the list of words in `word_store.h` since we are splitting the words with `-` in the test case

**Comment by cieslarmichal** [comment]
Ok lets remove dash from thoses words so it would be ebook
