### ISSUE TITLE
add locale to internet module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#891]
ref book module

**Comment by layasri157** [comment]
i would like to work on it. please assign it too

**Comment by cieslarmichal** [comment]
Assigned

**Comment by cieslarmichal** [comment]
any progress?

**Comment by SgtApone117** [comment]
Hi, can i work on this issue?

**Comment by cieslarmichal** [comment]
Yup, assigned

**Comment by SgtApone117** [comment]
I have opened a PR, could you please review the changes for me? thank you
