### ISSUE TITLE
add locale to music module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#892]
ref book module

**Comment by harshini1807** [comment]
id like to work on this.please assign it to me

**Comment by cieslarmichal** [comment]
Ok assigned

**Comment by SgtApone117** [comment]
Hi, Can i work on this issue

**Comment by cieslarmichal** [comment]
Yes, go ahead :)

**Comment by SgtApone117** [comment]
I have opened the PR for this issue, Can you please review it?
Thank you
