### ISSUE TITLE
add locale to medicine module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#894]
ref book module

**Comment by harshini1807** [comment]
id like to work on this.plz assign it to me.i would be very keen to work upon this

**Comment by cieslarmichal** [comment]
Ok assigned

**Comment by cieslarmichal** [comment]
any progress?

**Comment by gustavobastian** [comment]
Hi @cieslarmichal., Can I work in this issue? Could you assign it to me?

**Comment by cieslarmichal** [comment]
Assigned
