### ISSUE TITLE
add locale to movie module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#895]
ref book module

**Comment by SgtApone117** [comment]
Hey, i want to work on this. Thank you

**Comment by cieslarmichal** [comment]
any progress?

**Comment by SgtApone117** [comment]
Hi michael, i would complete in couple of days. Sorry for the delay. Thank you.

**Comment by SgtApone117** [comment]
I referred the book module, do I have to also implement for Pl-pl version like a default version apart from en-us?

**Comment by cieslarmichal** [comment]
No you dont have but it would be nice to add one more locale than english, doesnt have to be polish
