### ISSUE TITLE
add locale to sport module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#897]
ref book module

**Comment by harshini1807** [comment]
Kindly assign this to me too. Ill gladly complete all four tasks under Hacktoberfest ASAP..Ill also help out with other tasks after completing these

**Comment by cieslarmichal** [comment]
Ok, assigned

**Comment by cieslarmichal** [comment]
any progress?

**Comment by gustavobastian** [comment]
Hi, @cieslarmichal, Can I work in this issue? Could you assign it to me?

**Comment by cieslarmichal** [comment]
Sure

**Comment by cieslarmichal** [comment]
Assigned
