### ISSUE TITLE
fix codecov in word data

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#905]
![image](https://github.com/user-attachments/assets/b0cdb91c-8d2a-46e4-87a0-21c6b09fb998)

**Comment by Itachi0906** [comment]
Hi! Can you elaborate more on this issue I would like to work on it

**Comment by layasri157** [comment]
i want to work on it. please assign it to me

**Comment by cieslarmichal** [comment]
Assigned

**Comment by cieslarmichal** [comment]
any progress?

**Comment by Itachi0906** [comment]
Hi, sorry haven't been getting the time to work on it.
Will get back on it as soon as I can .

**Comment by MadhurSaluja** [comment]
@cieslarmichal can u pls give a little more detail and assign this issue to me?
