### ISSUE TITLE
fix codecov in commerce test

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#907]
![image](https://github.com/user-attachments/assets/e224cdd8-d100-4980-821b-b75660aefe5f)

**Comment by diya-kishore** [comment]
Kindly assign this to me too. Ill gladly complete all four tasks under Hacktoberfest ASAP..Ill also help out with other tasks after completing these

**Comment by cieslarmichal** [comment]
Assigned

**Comment by mayank-Pareek** [comment]
Hi @cieslarmichal, since there has been no progress on this for a long time, can you please assign this to me.

**Comment by cieslarmichal** [comment]
Sure assigned
