### ISSUE TITLE
fix codecov in git test

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#908]
![image](https://github.com/user-attachments/assets/d3232ff6-91ab-4ebe-846f-96f7302f168e)

**Comment by 00thirdeye00** [comment]
@cieslarmichal since its in the test case, can we remove the check?

**Comment by cieslarmichal** [comment]
It just extracts the number from string which has string+number like "ISSUE50", and we need the number, we could just delete letters from string and parse as number or similar.
