### ISSUE TITLE
move "binary" function from string module to number module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#912]

**Comment by SayeedKhan21** [comment]
Hi @cieslarmichal could u describe more about this issue  ? I would want to start working on this

**Comment by cieslarmichal** [comment]
Hello, we just need to move function from one module to another,  need to move function from string.h to number.h and implementation string.cpp to number.cpp and tests from number_test.cpp to string_test.cpp

**Comment by SayeedKhan21** [comment]
Which function are u talking about. ? like string.h is pretty different from number.h right ? (just casually looked at code dunno much in detail)

**Comment by cieslarmichal** [comment]
Like in issue title "binary" function

**Comment by SayeedKhan21** [comment]
ok thanks , hey do u suggest anything which would make my code understanding better ? or should i just keep contributing  which eventually would help me with understanding ?

**Comment by SayeedKhan21** [comment]
hey when u say move does it mean that the functions should not be present in string.h ? like do i need to remove them from string.h ?

**Comment by cieslarmichal** [comment]
Yup just cut from one place, paste on the other. Then build run tests, if everything is ok submit a PR

**Comment by cieslarmichal** [comment]
You can do those simple changes and then you can pick something more difficult and you will learn by doing

**Comment by SayeedKhan21** [comment]
also u mentioned that i need to move tests from number_test to string_test , is it correct or the other way around ? tests related to binary function should be moved from string_test to number_test right ?

**Comment by cieslarmichal** [comment]
Right good catch, typo

**Comment by SayeedKhan21** [comment]
also regarding tests  , i need to go into ./build/tests/faker-cxx-UT right ? in the instructions it just tells to do ./faker-cxx-UT , however it is not present in the root folder at that time , atleast it happened for me in that way

**Comment by SayeedKhan21** [comment]
Also i cannot find any file named number.cpp in entire project , could u plz tell me about this file ?

**Comment by cieslarmichal** [comment]
yeah ./build/tests/faker-cxx-UT, you could make changes to instruction as well if its wrong somehow 👍 
about cpp file, you are right, its a header only module, forgot about that, so changes would include number.h and number_test.cpp

**Comment by SayeedKhan21** [comment]
But if we are not implementing it in number.cpp whats the use of declaring binary function in it ?

**Comment by SayeedKhan21** [comment]
how do i make changes in readme , do i need to raise a PR for that as well , there are two changes as per me 
1) regarding ./faker-cxx-UT 
2) llvm version must be atleast 20 to support std::floating_point

**Comment by cieslarmichal** [comment]
Yup in seperate PR

**Comment by cieslarmichal** [comment]
We should move implementation from string.cpp to number.h

**Comment by SayeedKhan21** [comment]
Umm i am getting a bit confused here . U want me to move entire string.cpp to number.h ? the code inside number.h seems very diff from string.cpp logically , could u plz explain a bit more precisely if possible ?

**Comment by cieslarmichal** [comment]
there is a binary function: https://github.com/cieslarmichal/faker-cxx/blob/3e15ba5b9cec4d18a1dbe33ffb74df6c8343a823/include/faker-cxx/string.h#L377 (with overload 2 of them), move it to number.h file with their implementations: https://github.com/cieslarmichal/faker-cxx/blob/3e15ba5b9cec4d18a1dbe33ffb74df6c8343a823/src/modules/string.cpp#L359

**Comment by SayeedKhan21** [comment]
` FAKER_CXX_EXPORT std::string binary(int min, int max); `
does this line need to be copied as it is in number.h ?

**Comment by cieslarmichal** [comment]
Yeah I think so

**Comment by SayeedKhan21** [comment]
number.h also has floating point template declarations for every functions ,  what abt it. ?

**Comment by cieslarmichal** [comment]
I don't think you need to change anything about those

**Comment by SayeedKhan21** [comment]
Hey man quick ques , i also need to copy all the dependent functions inside implementation of  function binary right ? 

Also could u tell me how do i import src/common/algo_helper.h inside include/faker-cxx/number.h , when i add a statement
`include "..src/common/algo_helper.h"` it gives me error saying file not found

**Comment by cieslarmichal** [comment]
you should create number.cpp file and add this implementation there, lets maybe go to discord so it would be easier and more responsive :D

**Comment by cieslarmichal** [comment]
just add declaration in header file and implementation in cpp file

**Comment by cieslarmichal** [comment]
and should be fine
