### ISSUE TITLE
move "octal" function from string module to number module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#913]

**Comment by gagankonana** [comment]
Hi @cieslarmichal, had a quick question, there are two "octal" functions in the string module, do we want to move both of them to number here?

**Comment by cieslarmichal** [comment]
Hello @gagankonana there should be only one octal function in repo, the guarantee one is legacy and already removed from header file (some leftovers in cpp file), could you please remove leftovers of guarantee overload?
