### ISSUE TITLE
add nanoId function to string module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#927]

**Comment by 00thirdeye00** [comment]
What is 'nanold' function⁉️

**Comment by cieslarmichal** [comment]
it's unique identifier like uuid but simpler and more human-readable, example: https://www.npmjs.com/package/nanoid

**Comment by cieslarmichal** [comment]
fakerjs: https://github.com/faker-js/faker/blob/4a8499a1630444ea5b2463cf3e2d687db6980428/src/modules/string/index.ts#L723

**Comment by cieslarmichal** [comment]
Hello, sure go ahead :) assigned
