### ISSUE TITLE
add anytime to Date module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#936]
like https://fakerjs.dev/api/date.html#anytime

**Comment by tonykcao** [comment]
PR made #947

**Comment by cieslarmichal** [comment]
Good changes, please fix some failing tests

**Comment by tonykcao** [comment]
@cieslarmichal new fix and tests added! We had an unexpected case of Y2K38 (which explains why its visible here and not in the js version)
