### ISSUE TITLE
add between function to Date module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#937]
like https://fakerjs.dev/api/date.html#between

**Comment by cieslarmichal** [comment]
There is no API for this in header file its just internal function, so users cannot use it. The new public API should work probably with two timestamps or iso dates :)

**Comment by cieslarmichal** [comment]
I have assigned you.

**Comment by tonykcao** [comment]
Hi! I'll be taking some time off soon, someone else feel free to take this in the mean time!

**Comment by cieslarmichal** [comment]
Ok :)

**Comment by Mounayer** [comment]
Hello, I could give this issue a try!

**Comment by cieslarmichal** [comment]
Ok, assigned :)
