### ISSUE TITLE
add ordinalDirection function to Location module 

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#939]
like https://fakerjs.dev/api/location.html#ordinaldirection

**Comment by Nystana** [comment]
Hello, I'd like to try this issue

**Comment by cieslarmichal** [comment]
Ok, go ahead :) assigned

**Comment by cieslarmichal** [comment]
Consider giving a star to the repository to make this project more popular 😎

**Comment by cieslarmichal** [comment]
any progress?

**Comment by cieslarmichal** [comment]
hello, yes its still TODO, assigned

**Comment by cieslarmichal** [comment]
Consider also giving a star to the repository & joining discord channel!
