### ISSUE TITLE
add checking formatting in pipeline

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#953]
create a github action workflow with running clang format and checking if everything is formatted correctly

**Comment by diya-kishore** [comment]
Kindly assign this to me. very keen to work upon

**Comment by cieslarmichal** [comment]
Assigned

**Comment by cieslarmichal** [comment]
hello any progress?

**Comment by mayank-Pareek** [comment]
Hi @cieslarmichal, this issue was not being worked on for a long time so I have created a pull request to close this.
