### ISSUE TITLE
fix image module docs

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#954]
doxygen is not generating docs for image module correctly: https://cieslarmichal.github.io/faker-cxx/image_8h.html

**Comment by DeepanshuT25** [comment]
hey, I want to work on this can you assign me and give me some path

**Comment by cieslarmichal** [comment]
https://cieslarmichal.github.io/faker-cxx/image_8h.html

**Comment by MadhurSaluja** [comment]
@cieslarmichal  can I work on this pls?

**Comment by cieslarmichal** [comment]
Yes
