### ISSUE TITLE
add continent function to location module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#959]

**Comment by s16malik** [comment]
Hello, I'd like to work on this issue.

**Comment by charan-003** [comment]
i want to work on this

**Comment by cieslarmichal** [comment]
Ok assigned

**Comment by charan-003** [comment]
just wanted to confirm that i need to change files in location.cpp, location_data.h and test files right

**Comment by cieslarmichal** [comment]
Yes

**Comment by cieslarmichal** [comment]
Hello, please make changes in one PR instead of 4 :) it womt work that way
