### ISSUE TITLE
update git submodules to latest version

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#960]
update versions of gtest and fmt libs

**Comment by Devansh-Negi3839** [comment]
@cieslarmichal Could you please assign this?

**Comment by cieslarmichal** [comment]
Yes, assigned

**Comment by Devansh-Negi3839** [comment]
@cieslarmichal 
Could you please check this?
https://github.com/cieslarmichal/faker-cxx/pull/961
