### ISSUE TITLE
Add person first and last names data from Czech

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#98]

**Comment by SunHashira** [comment]
Hi, can I help you with this issue ?

**Comment by cieslarmichal** [comment]
Hello, sure, assigned :)

**Comment by cieslarmichal** [comment]
hey, how is it going?

**Comment by SunHashira** [comment]
Hi, a got some issues with my PC, you can unsign this issue but if its alright i would still love to work on that vehicle module (its also because of my school) but my pc will be fixed in monday-tuesday so it will be done till wednesday.

**Comment by cieslarmichal** [comment]
Ok so I will unassign this and vehicle module is yours :)
