### ISSUE TITLE
fix imageUrl in Image module to generate images from picsum photos

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#990]
replace https://loremflickr.com with https://picsum.photos/ and test if it works and generates different images for given categories

**Comment by bitalec** [comment]
Hi. I'm new to open source contributions and would like to try working on this issue.
Could you please assign this issue to me?

**Comment by cieslarmichal** [comment]
Sure, assigned

**Comment by bitalec** [comment]
Hi, I have a question.

I saw that picsum.photos doesn’t let you generate random images by category (like dogs, tech, etc.). It only gives random images or images by ID.

Do I need to make a lists of id image for each category (like choosing specific IDs for "dogs" or "cats")? Or is there an easier way to do this?

Thanks for your help!

**Comment by cieslarmichal** [comment]
lets maybe refactor it to seperate methods like in fakerjs:

![image](https://github.com/user-attachments/assets/1797468b-9124-4969-991c-6b3a12d2135b)

so picsum and flickr would have seperate methods and url would get random either picsum or flickr

**Comment by bitalec** [comment]
Hi, I added the urlPicsumPhotos method to generate images from https://picsum.photos/.
Can I also change the name of the imageUrl method?
Should I add the tests in a separate commit, or is it fine to include them in the same one?

**Comment by bitalec** [comment]
I, i have this problem 
`git push origin feature/PicsumPhotos
ERROR: Permission to cieslarmichal/faker-cxx.git denied to bitalec.
`
